name: buildBlazorApp

on: push

jobs:
  install-nuget:
    runs-on: windows-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v4
      # install dot net
      - name: install .net version
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '8.x'

      # build application
      - name: build application
        run: dotnet build
        working-directory: ./GitHubActionBlazorApp

      # unit test
      - name: run unit tests
        run: dotnet test
        working-directory: ./GitHubActionBlazorApp/GitHubActionBlazorApp.Tests
