name: buildBlazorApp

on: push

env:
  outputDir: './BlazorApp'

jobs:
  BlazorApp-CI:
    runs-on: windows-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v4
      # install dot net
      - name: install .net version
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '8.x'

      # build application
      - name: build application
        run: |
          cd GitHubActionBlazorApp
          dotnet build
          dotnet publish -c Release -o ${{ env.outputDir }}
      # list files
      - name: list files
        run: |
          cd GitHubActionBlazorApp
          ls -R
      # unit test
      - name: run unit tests
        run: |
          cd GitHubActionsBlazorApp.Test
          dotnet test
