name: buildBlazorApp

on: push

env:
  outputDir: './BlazorApp'
  AZURE_WEBAPP_NAME: BlazorApp
  AZURE_WEBAPP_PACKAGE_PATH: './BlazorApp'

jobs:
  BlazorApp-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v4
      # install dot net
      - name: install .net version
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '8.x'

      # build application
      - name: build application
        run: |
          cd GitHubActionBlazorApp
          dotnet build
          dotnet publish -c Release -o ${{ env.outputDir }} -r r linux-x64 --self-contained true /p:UseAppHost=true

      # unit test
      - name: run unit tests
        run: |
          cd GitHubActionsBlazorApp.Test
          dotnet test

  BlazorApp-CD:
    runs-on: ubuntu-latest
    needs: BlazorApp-CI
    steps:
      - name: Deploy to Azure App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
